# Generated by Django 2.2.1 on 2019-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='temporder',
            name='userID',
        ),
        migrations.AlterField(
            model_name='temporder',
            name='orderID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
